# Generated by Django 5.2.3 on 2026-06-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colecciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colecciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'localidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'materias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'municipios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_module.localidades')),
            ],
            options={
                'db_table': 'lugares',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_patrimonio/')),
                ('signatura', models.TextField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio', models.SmallIntegerField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotografias_autor_set', to='management_module.autores')),
                ('autor_fondo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_fondo_set', to='management_module.autores')),
                ('coleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_module.colecciones')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotografias_lugar_set', to='management_module.lugares')),
            ],
            options={
                'db_table': 'fotografias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FotografiasMaterias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fotografia_signatura', models.ForeignKey(db_column='fotografia_signatura', on_delete=django.db.models.deletion.CASCADE, to='management_module.fotografias')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_module.materias')),
            ],
            options={
                'db_table': 'fotografias_materias',
                'managed': True,
                'unique_together': {('fotografia_signatura', 'materia')},
            },
        ),
        migrations.AddField(
            model_name='fotografias',
            name='materias',
            field=models.ManyToManyField(related_name='fotografias', through='management_module.FotografiasMaterias', to='management_module.materias'),
        ),
        migrations.AddField(
            model_name='localidades',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_module.municipios'),
        ),
        migrations.CreateModel(
            name='FotografiasPersonas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fotografia_signatura', models.ForeignKey(db_column='fotografia_signatura', on_delete=django.db.models.deletion.CASCADE, to='management_module.fotografias')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_module.personas')),
            ],
            options={
                'db_table': 'fotografias_personas',
                'managed': True,
                'unique_together': {('fotografia_signatura', 'persona')},
            },
        ),
        migrations.AddField(
            model_name='fotografias',
            name='personas',
            field=models.ManyToManyField(related_name='fotografias', through='management_module.FotografiasPersonas', to='management_module.personas'),
        ),
    ]
