# Generated by Django 5.2.3 on 2026-06-23 23:11

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('management_module', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
